name: Build and Deploy to Codeberg Pages

on:
  push:
    branches:
      - main  # or whatever branch you want to trigger on
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: CODEBERG

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and Build
        working-directory: v2
        run: |
          npm install
          npm install firebase
          node src/gen-sitemap.js
          git init 
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add . 
          git commit -m "Generate Sitemap" 
          git push --force origin main
          npm run build

      - name: Deploy to Codeberg Pages
        run: |
          cd v2/dist
          git add .
          git commit -m "Deploy from GitHub Actions"
          git branch -M main
          git remote add origin https://KRXZY_KRXZY:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/snaplabs/pages.git
          git push --force origin main
