name: Build Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write  # Needed to push back

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Generate Sitemap and Commit
        working-directory: v2
        run: |
          npm install
          node src/gen-sitemap.mjs

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          if [ -f public/sitemap.xml ]; then
            git add public/sitemap.xml
          elif [ -f sitemap.xml ]; then
            git add sitemap.xml
          fi

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Generate Sitemap"
            git push origin main
          fi
